CREATE TABLE feed
(
    number BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),

    user_id VARCHAR(255) NOT NULL,

    title VARCHAR(255) NOT NULL,

    content VARCHAR(32672) NOT NULL,

    locked BOOLEAN NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);