CREATE TABLE profile
(
	number BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
	
	id VARCHAR(255) NOT NULL UNIQUE,
	
	name VARCHAR(255) NOT NULL,
	
	sex INT NOT NULL,
	
	age INT NOT NULL,
	
	locked BOOLEAN NOT NULL,
	
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
